# Compose file for the GROS data gathering agent.
#
# When starting this application manually in the BigBoat Docker dashboard,
# ensure that you have all the credentials (usernames, passwords, tokens)
# and other parameters (project names, source locations) that you are prompted.
#
# You may be able to leave out some of these credentials. For example, a dropins
# file store and MonetDB database are not necessary to have in a project.
#
# Supply a dash (-) in for unused parameters to indicate that the value is
# empty. The BigBoat UI does not allow leaving parameters empty (IQT-1456).

agent:
  image: $DOCKER_REGISTRY/gros-data-gathering
  volumes:
    - /agent/home/agent/export:/home/agent/export
  environment:
    - JIRA_SERVER=https://{{JIRA_SERVER}}/jira/
    - JIRA_USER={{JIRA_REPORTER}}
    - JIRA_PASSWORD={{JIRA_PASSWORD}}
    - DEFINITIONS_TYPE=subversion
    - DEFINITIONS_NAME=kwaliteitsmetingen
    - DEFINITIONS_URL=http://{{SVN_SERVER}}/commons/algemeen/kwaliteitsmetingen/trunk/
    - DEFINITONS_PATH=kwaliteitsmetingen/trunk
    - HISTORY_URL=http://{{JENKINS_SERVER}}/view/Quality%20reports/job/create-full-history/ws/
    - HISTORY_PATH=/var/jenkins/workspace/create-full-history/
    - GITLAB_URL=http://www.gitlab.{{PROJECT_NAME}}.example/
    - GITLAB_TOKEN={{GITLAB_API_TOKEN}}
    - DROPINS_STORE=owncloud
    - DROPINS_URL=http://www.owncloud.{{PROJECT_NAME}}.example/
    - DROPINS_USER={{DROPINS_USER}}
    - DROPINS_PASSWORD={{DROPINS_PASSWORD}}
    - MONETDB_USER={{MONETDB_USER}}
    - MONETDB_PASSWORD={{MONETDB_PASSWORD}}
    - MONETDB_HOST={{MONETDB_SERVER}}
    - MONETDB_NAME=gros
    - SSH_USERNAME=agent-{{JIRA_KEY}}
    - SSH_HOST={{SSH_HOST}}
    - SSH_HTTPS_CERT=certs/gros.crt
    - IMPORTER_URL=http://{{JENKINS_SERVER}}/view/GROS/job/build-importerjson/lastSuccessfulBuild/artifact/Code/importerjson/dist/*zip*/dist.zip
    - JIRA_KEY={{JIRA_KEY}}
    - PROJECT_NAME={{PROJECT_NAME}} #${BIGBOAT_PROJECT}
    - SUBPROJECT_KEY={{SUBPROJECT_KEY}}
    - SOURCE_HOST=www.gitlab.{{PROJECT_NAME}}.example
    - SOURCE_USERNAME={{SOURCE_USERNAME}}
    - SOURCE_PASSWORD={{SOURCE_PASSWORD}}
    - SOURCE_TOKEN={{SOURCE_GITLAB_TOKEN}}
    - SOURCE_TFS={{SOURCE_TFS}}
    - CRON_PERIOD=weekly
