# Compose file for the GROS data gathering agent.
#
# When (re)starting this application in the BigBoat Docker dashboard,
# the agent may need additional credentials (usernames, passwords, tokens)
# and other parameters (project names, source locations) to function.
#
# These parameters may have already been filled in, but check the agent web UI
# to confirm after restarting. You can find the agent configuration web UI
# under the instance in the "www" section. More hints are provided there.

agent:
  image: $DOCKER_REGISTRY/gros-data-gathering:latest
  volumes:
    - /agent/home/agent/export:/home/agent/export
    - /agent/home/agent/config:/home/agent/config
    - /agent/home/agent/.ssh:/home/agent/.ssh
  environment:
    - CRON_PERIOD=daily
www:
  image: $DOCKER_REGISTRY/gros-agent-config
  volumes:
    - /agent/home/agent/export:/home/agent/export
    - /agent/home/agent/config:/home/agent/config
    - /agent/home/agent/.ssh:/home/agent/.ssh
  environment:
    - EXPORT_PATH=/home/agent/export
    - CONFIG_PATH=/home/agent/config
    - IDENTITY_PATH=/home/agent/.ssh
    - LISTEN_ADDR=0.0.0.0
